sdk: "/Users/jmalonzo/Code/mobile/rhodes"
sdkversion: 2.1.0
name: rhodes-google-analytics
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator4.1
  provisionprofile:
  codesignidentity:
  entitlements:
extensions: ["json", "analytics"]
